# Generated by Django 6.0.4 on 2026-05-22 15:37

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Familya')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email/Gmail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Telefon raqam')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil rasimi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yashash manzili')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superadmin statusi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodimlik statusi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil aktivligi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maxsulot narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsulot Surati')),
                ('in_stock', models.IntegerField(default=1, verbose_name='Ombordagi soni')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Maxsulot Tavsifi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_one.category', verbose_name='Maxsulot Kategoryasi')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='maxsulot soni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Xarid vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchini')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.product', verbose_name='Maxsulot nomini')),
            ],
            options={
                'verbose_name': 'Savatchadagi maxsulot',
                'verbose_name_plural': 'Savatchadagi maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Maxsulot nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sariflangan pul miqdori')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Xarid vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': "Tranzaksiyalar-(O'tkazmalar)",
                'ordering': ['-created'],
            },
        ),
    ]
