# Generated by Django 6.0.4 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Ombordagi soni'),
        ),
    ]
