# Generated by Django 6.0.4 on 2026-05-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0014_alter_transaction_amount_alter_transaction_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created'], 'verbose_name': 'Tranzaksiya', 'verbose_name_plural': "Tranzaksiyalar-(O'tkazmalar)"},
        ),
    ]
